<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'OspariAdmin\Module'                       => __DIR__ . '/Module.php',
    'OspariAdmin\Controller\AuthController'    => __DIR__ . '/src/OspariAdmin/Controller/AuthController.php',
    'OspariAdmin\Controller\BaseController'    => __DIR__ . '/src/OspariAdmin/Controller/BaseController.php',
    'OspariAdmin\Controller\DraftController'   => __DIR__ . '/src/OspariAdmin/Controller/DraftController.php',
    'OspariAdmin\Controller\InstallController' => __DIR__ . '/src/OspariAdmin/Controller/InstallController.php',
    'OspariAdmin\Controller\MediaController'   => __DIR__ . '/src/OspariAdmin/Controller/MediaController.php',
    'OspariAdmin\Controller\SettingController' => __DIR__ . '/src/OspariAdmin/Controller/SettingController.php',
    'OspariAdmin\Controller\UserController'    => __DIR__ . '/src/OspariAdmin/Controller/UserController.php',
    'OspariAdmin\Mailer'                       => __DIR__ . '/src/OspariAdmin/etc/Mailer.php',
    'OspariAdmin\Helper\AlertHelper'           => __DIR__ . '/src/OspariAdmin/Helper/AlertHelper.php',
    'OspariAdmin\Model\Draft'                  => __DIR__ . '/src/OspariAdmin/Model/Draft.php',
    'OspariAdmin\Model\Draft2Media'            => __DIR__ . '/src/OspariAdmin/Model/Draft2Media.php',
    'OspariAdmin\Model\Media'                  => __DIR__ . '/src/OspariAdmin/Model/Media.php',
    'OspariAdmin\Model\Post'                   => __DIR__ . '/src/OspariAdmin/Model/Post.php',
    'OspariAdmin\Model\Setting'                => __DIR__ . '/src/OspariAdmin/Model/Setting.php',
    'OspariAdmin\Model\Tag'                    => __DIR__ . '/src/OspariAdmin/Model/Tag.php',
    'OspariAdmin\Model\User'                   => __DIR__ . '/src/OspariAdmin/Model/User.php',
    'OspariAdmin\Service\SwiftMailer'          => __DIR__ . '/src/OspariAdmin/Service/SwiftMailer.php',
);