<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Ospari\Module'                     => __DIR__ . '/Module.php',
    'Ospari\Controller\AssetController' => __DIR__ . '/src/Ospari/Controller/AssetController.php',
    'Ospari\Controller\BaseController'  => __DIR__ . '/src/Ospari/Controller/BaseController.php',
    'Ospari\Controller\PostController'  => __DIR__ . '/src/Ospari/Controller/PostController.php',
    'Ospari\Helper\TagCollection'       => __DIR__ . '/src/Ospari/helper/TagCollection.php',
    'Ospari\Helper\Theme'               => __DIR__ . '/src/Ospari/helper/Theme.php',
    'Ospari\Model\Draft'                => __DIR__ . '/src/Ospari/Model/Draft.php',
    'Ospari\Model\Post'                 => __DIR__ . '/src/Ospari/Model/Post.php',
    'Ospari\Model\User'                 => __DIR__ . '/src/Ospari/Model/User.php',
);